create table if not exists users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    picture_url varchar(255)
);

create table if not exists product_info (
    product_id bigint primary key,
    name varchar(255) not null,
    price double precision not null
);

create table if not exists orders (
    id bigint generated by default as identity primary key,
    status varchar(255) not null,
    date_created timestamp default current_timestamp
);

create table if not exists orders_date(
    order_id bigint not null,
    status varchar(255) not null,
    created_at date default current_date
); 

create table if not exists order_product (
    order_id bigint references orders(id),
    product_id bigint references product_info(product_id),
    quantity bigint not null,
    primary key (order_id, product_id)
);

