name: Main workflow
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Repair Flyway schema history
      run: |
        docker run --rm \
          -v $(pwd)/migrations:/flyway/sql \
          flyway/flyway \
          -url="jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}" \
          -user="${{ secrets.DB_USER }}" \
          -password="${{ secrets.DB_PASSWORD }}" \
          repair -X

    - name: Check table structure and Flyway history after Repair
      env:
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        echo "--- Describing product table after repair ---"
        docker run --rm --network host postgres:16 psql -h "${{ secrets.DB_HOST }}" -p "${{ secrets.DB_PORT }}" -U "${{ secrets.DB_USER }}" -d "${{ secrets.DB_NAME }}" -c "\d product" || echo "Product table not found or psql error"
        echo "--- Flyway schema history after repair ---"
        docker run --rm --network host postgres:16 psql -h "${{ secrets.DB_HOST }}" -p "${{ secrets.DB_PORT }}" -U "${{ secrets.DB_USER }}" -d "${{ secrets.DB_NAME }}" -c "SELECT * FROM flyway_schema_history ORDER BY installed_rank;" || echo "Flyway history not found or psql error"

    - name: Apply migrations with Flyway
      run: |
        docker run --rm \
          -v $(pwd)/migrations:/flyway/sql \
          flyway/flyway \
          -url="jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}" \
          -user="${{ secrets.DB_USER }}" \
          -password="${{ secrets.DB_PASSWORD }}" \
          migrate -X

    - name: Check table structure and Flyway history after Migrate
      env:
        PGPASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        echo "--- Describing product table after migrate ---"
        docker run --rm --network host postgres:16 psql -h "${{ secrets.DB_HOST }}" -p "${{ secrets.DB_PORT }}" -U "${{ secrets.DB_USER }}" -d "${{ secrets.DB_NAME }}" -c "\d product" || echo "Product table not found or psql error"
        echo "--- Flyway schema history after migrate ---"
        docker run --rm --network host postgres:16 psql -h "${{ secrets.DB_HOST }}" -p "${{ secrets.DB_PORT }}" -U "${{ secrets.DB_USER }}" -d "${{ secrets.DB_NAME }}" -c "SELECT * FROM flyway_schema_history ORDER BY installed_rank;" || echo "Flyway history not found or psql error"

    - name: Download and setup autotests binaries
      run: |
        wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
        chmod +x ./dbopstest
        mv ./dbopstest /usr/local/bin/dbopstest

    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}