name: Main workflow
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check secrets
      run: |
        if [ -z "${{ secrets.DB_HOST }}" ]; then echo "DB_HOST is not set"; exit 1; fi
        if [ -z "${{ secrets.DB_PORT }}" ]; then echo "DB_PORT is not set"; exit 1; fi
        if [ -z "${{ secrets.DB_NAME }}" ]; then echo "DB_NAME is not set"; exit 1; fi
        if [ -z "${{ secrets.DB_USER }}" ]; then echo "DB_USER is not set"; exit 1; fi
        if [ -z "${{ secrets.DB_PASSWORD }}" ]; then echo "DB_PASSWORD is not set"; exit 1; fi
        echo "All secrets are set"

    - name: Repair Flyway checksum
      run: |
        echo "Repairing Flyway checksum in database"
        docker run --rm \
          -v $(pwd)/migrations:/flyway/sql \
          flyway/flyway:9.8.1 \
          -url="jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}" \
          -user="${{ secrets.DB_USER }}" \
          -password="${{ secrets.DB_PASSWORD }}" \
          repair

    - name: Apply migrations with Flyway
      run: |
        echo "Trying to connect to: jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}"
        docker run --rm \
          -v $(pwd)/migrations:/flyway/sql \
          flyway/flyway:9.8.1 \
          -url="jdbc:postgresql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}" \
          -user="${{ secrets.DB_USER }}" \
          -password="${{ secrets.DB_PASSWORD }}" \
          migrate

    - name: Download and setup autotests binaries
      run: |
        wget -qO- cloud-services-engineer.gitlab.yandexcloud.net/practicum-cloud-services/dbops-autotests/-/package_files/1/download > dbopstest
        chmod +x ./dbopstest
        mv ./dbopstest /usr/local/bin/dbopstest

    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}